// <auto-generated />
namespace Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relationCourseStudentGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationCourseStudentGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201801091813214_relation-Course-StudentGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
